


CLASS zbp_i_quality_inspection_root DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_quality_inspection_root.

CLASS-DATA: total_price_up TYPE p DECIMALS 2 VALUE 0.



ENDCLASS.



CLASS ZBP_I_QUALITY_INSPECTION_ROOT IMPLEMENTATION.
ENDCLASS.
